import { Transaction, TransactionScope, TransactionType, PriorityBill } from "./types";

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // ------------------ MAY 2026 ------------------
  {
    id: "m1",
    date: "2026-05-02",
    description: "Honorários Sucumbência - Processo 1032840-SP",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Honorários de Sucumbência",
    amount: 14200.00,
    paymentMethod: "Transferência Bancária",
    notes: "Honorários vencidos na ação contra Banco X",
  },
  {
    id: "m2",
    date: "2026-05-05",
    description: "Aluguel da Sala Comercial 901",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Aluguel e Condomínio do Escritório",
    amount: 2800.00,
    paymentMethod: "Boleto Bancário",
    notes: "Aluguel mensal escritório sede",
  },
  {
    id: "m3",
    date: "2026-05-06",
    description: "Condomínio Comercial",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Aluguel e Condomínio do Escritório",
    amount: 720.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "m4",
    date: "2026-05-08",
    description: "Assinatura Mensal JurisWay & Astrea",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Sistemas Judiciais e Softwares (LegalTech)",
    amount: 320.00,
    paymentMethod: "Cartão de Crédito",
  },
  {
    id: "m5",
    date: "2026-05-10",
    description: "Honorários Contratuais - Dr. André Advogados",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Honorários Contratuais",
    amount: 5500.00,
    paymentMethod: "PIX",
    notes: "Assessoria mensal jurídica",
  },
  {
    id: "m6",
    date: "2026-05-12",
    description: "Supermercado Carrefour Doméstico (CONTA ESCRITÓRIO)",
    type: TransactionType.EXPENSE,
    // INITIALLY MIXED: bought personal supermarket on office account!
    scope: TransactionScope.PERSONAL,
    category: "Alimentação e Supermercados",
    amount: 450.00,
    paymentMethod: "Cartão de Crédito",
    notes: "Alerta: Comprado acidentalmente no cartão do escritório!",
    isAiCategorized: true,
  },
  {
    id: "m7",
    date: "2026-05-15",
    description: "Retirada de Pró-labore Sócios",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Equipe, Associados e Pró-labore",
    amount: 6000.00,
    paymentMethod: "Transferência Bancária",
    notes: "Repasse de lucros aos fundadores",
  },
  {
    id: "m8",
    date: "2026-05-15",
    description: "Parceiro Dr. Silvano - Divisão de Honorários",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Equipe, Associados e Pró-labore",
    amount: 2500.00,
    paymentMethod: "PIX",
  },
  {
    id: "m9",
    date: "2026-05-15",
    description: "Retirada Sócios - Conta Pessoal",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PERSONAL,
    category: "Retirada de Pró-labore/Lucros",
    amount: 6000.00,
    paymentMethod: "Transferência Bancária",
  },
  {
    id: "m10",
    date: "2026-05-18",
    description: "Escola de Música do Filho (CONTA ESCRITÓRIO)",
    type: TransactionType.EXPENSE,
    // MIXED: bought personal on office
    scope: TransactionScope.PERSONAL,
    category: "Educação e Livros",
    amount: 320.00,
    paymentMethod: "Débito Automático",
    notes: "Alerta: Débito em conta PJ do escritório!",
    isAiCategorized: true,
  },
  {
    id: "m11",
    date: "2026-05-20",
    description: "Custas Judiciais Guia TJSP - Recurso de Apelação",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Custas Processuais e Diligências",
    amount: 830.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "m12",
    date: "2026-05-22",
    description: "Shopping Iguatemi - Jantar Familiar de Lazer",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PERSONAL,
    category: "Lazer, Viagens e Hobbies",
    amount: 290.00,
    paymentMethod: "PIX",
  },

  // ------------------ JUNE 2026 ------------------
  {
    id: "j1",
    date: "2026-06-01",
    description: "Consultoria Trabalhista - Empresa Alfa",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Consultoria e Pareceres",
    amount: 4000.00,
    paymentMethod: "PIX",
  },
  {
    id: "j2",
    date: "2026-06-03",
    description: "Anuidade OAB Secional",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Anuidade OAB e Serviços",
    amount: 920.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "j3",
    date: "2026-06-05",
    description: "Aluguel da Sala Comercial 901",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Aluguel e Condomínio do Escritório",
    amount: 2800.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "j4",
    date: "2026-06-05",
    description: "Condomínio Comercial",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Aluguel e Condomínio do Escritório",
    amount: 720.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "j5",
    date: "2026-06-06",
    description: "Honorários Contratuais - Metalúrgica Sul",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Honorários Contratuais",
    amount: 8500.00,
    paymentMethod: "PIX",
  },
  {
    id: "j6",
    date: "2026-06-08",
    description: "Assinatura Mensal JurisWay & Astrea",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Sistemas Judiciais e Softwares (LegalTech)",
    amount: 320.00,
    paymentMethod: "Cartão de Crédito",
  },
  {
    id: "j7",
    date: "2026-06-10",
    description: "Simples Nacional - Impostos do Escritório",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Impostos (Simples Nacional/Carnê-Leão)",
    amount: 1240.00,
    paymentMethod: "Boleto Bancário",
  },
  {
    id: "j8",
    date: "2026-06-12",
    description: "Livraria Jurídica - Doutrina Processual Civil",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Outras Despesas Profissionais",
    amount: 180.00,
    paymentMethod: "Cartão de Crédito",
  },
  {
    id: "j9",
    date: "2026-06-14",
    description: "Campanha de Marketing Legal - Google Ads",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Marketing e Divulgação",
    amount: 500.00,
    paymentMethod: "Cartão de Crédito",
  },
  {
    id: "j10",
    date: "2026-06-15",
    description: "Retirada de Pró-labore Sócios",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Equipe, Associados e Pró-labore",
    amount: 5000.00,
    paymentMethod: "Transferência Bancária",
  },
  {
    id: "j11",
    date: "2026-06-15",
    description: "Retirada Sócios - Conta Pessoal",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PERSONAL,
    category: "Retirada de Pró-labore/Lucros",
    amount: 5000.00,
    paymentMethod: "Transferência Bancária",
  },
  {
    id: "j12",
    date: "2026-06-15",
    description: "Supermercado Pão de Açúcar (CONTA ESCRITÓRIO)",
    type: TransactionType.EXPENSE,
    // MIXED: bought personal on office
    scope: TransactionScope.PERSONAL,
    category: "Alimentação e Supermercados",
    amount: 680.00,
    paymentMethod: "Cartão de Crédito",
    notes: "Alerta: Mistura patrimonial identificada pelo sistema!",
    isAiCategorized: true,
  },
  {
    id: "j13",
    date: "2026-06-16",
    description: "Netflix & Entretenimento Pessoal",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PERSONAL,
    category: "Lazer, Viagens e Hobbies",
    amount: 55.90,
    paymentMethod: "Cartão de Crédito",
  },
];

export const INITIAL_PRIORITY_BILLS: PriorityBill[] = [
  // --- SUBGRUPO R$ 3.971,09 ---
  {
    id: "pb-1-1",
    description: "Baia Maravilha",
    amount: 780.80,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Parcelamento baia lazer familiar",
  },
  {
    id: "pb-1-2",
    description: "Ressarcimento Roneiderson",
    amount: 1500.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Honorários associado de processo",
  },
  {
    id: "pb-1-3",
    description: "Seguro Solidy",
    amount: 150.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Seguro automotivo particular",
  },
  {
    id: "pb-1-4",
    description: "Rastreador Raiotek",
    amount: 60.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-5",
    description: "Entrada Acordo CAP",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-6",
    description: "Ressarcimento Gedson",
    amount: 750.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Dilgências de audiências de junho",
  },
  {
    id: "pb-1-7",
    description: "Plano de Saúde Seguros Unimed",
    amount: 480.29,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Convênio coparticipativo escritório",
  },

  // --- SUBGRUPO R$ 3.032,00 ---
  {
    id: "pb-2-1",
    description: "Maravilha maio",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-2",
    description: "Empréstimo Luan",
    amount: 200.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-3",
    description: "Curso Advocacia Odontológica Pai",
    amount: 250.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G2",
    notes: "Capacitação técnica direito na saúde",
  },
  {
    id: "pb-2-4",
    description: "Empréstimo PAI",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-5",
    description: "Excursão Barretos",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-6",
    description: "Karavella",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-7",
    description: "Cerveja Folia Facebeer",
    amount: 432.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-8",
    description: "Mula Katarina",
    amount: 400.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },

  // --- SUBGRUPO R$ 1.516,00 ---
  {
    id: "pb-3-1",
    description: "Contabilizei maio",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-2",
    description: "Contabilizei junho",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-3",
    description: "Acordo OAB abril",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-4",
    description: "Acordo OAB maio",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-5",
    description: "Acordo OAB junho",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-6",
    description: "Plano TIM",
    amount: 130.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },
  {
    id: "pb-3-7",
    description: "Plano VIVO maio",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-8",
    description: "Plano VIVO junho",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-9",
    description: "Óculos Pai 1 de 7",
    amount: 199.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },

  // --- ESPERAR (Total: R$ 6.507,00) ---
  {
    id: "pb-w-1",
    description: "Repasse Brunner",
    amount: 1800.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Parceria divisão de processos",
  },
  {
    id: "pb-w-2",
    description: "Óculos e Lente",
    amount: 1840.00,
    scope: TransactionScope.PERSONAL,
    status: "ESPERAR",
    groupType: "WAIT",
  },
  {
    id: "pb-w-3",
    description: "Ajustes VextriaHub",
    amount: 2000.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Prestação serviços TI LegalTech",
  },
  {
    id: "pb-w-4",
    description: "Mentoria Dr Antônio",
    amount: 867.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Mentoria de gestão estratégica",
  },
];
