import { Transaction, TransactionScope, TransactionType, PriorityBill } from "./types";

export const INITIAL_TRANSACTIONS: Transaction[] = [];

export const INITIAL_PRIORITY_BILLS: PriorityBill[] = [
  // --- SUBGRUPO R$ 3.971,09 ---
  {
    id: "pb-1-1",
    description: "Baia Maravilha",
    amount: 780.80,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Parcelamento baia lazer familiar",
  },
  {
    id: "pb-1-2",
    description: "Ressarcimento Roneiderson",
    amount: 1500.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Honorários associado de processo",
  },
  {
    id: "pb-1-3",
    description: "Seguro Solidy",
    amount: 150.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Seguro automotivo particular",
  },
  {
    id: "pb-1-4",
    description: "Rastreador Raiotek",
    amount: 60.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-5",
    description: "Entrada Acordo CAP",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-6",
    description: "Ressarcimento Gedson",
    amount: 750.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Diligências de audiências de junho",
  },
  {
    id: "pb-1-7",
    description: "Plano de Saúde Seguros Unimed",
    amount: 480.29,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Convênio coparticipativo escritório",
  },

  // --- SUBGRUPO R$ 3.032,00 ---
  {
    id: "pb-2-1",
    description: "Maravilha maio",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-2",
    description: "Empréstimo Luan",
    amount: 200.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-3",
    description: "Curso Advocacia Odontológica Pai",
    amount: 250.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G2",
    notes: "Capacitação técnica direito na saúde",
  },
  {
    id: "pb-2-4",
    description: "Empréstimo PAI",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-5",
    description: "Excursão Barretos",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-6",
    description: "Karavella",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-7",
    description: "Cerveja Folia Facebeer",
    amount: 432.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-8",
    description: "Mula Katarina",
    amount: 400.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },

  // --- SUBGRUPO R$ 1.516,00 ---
  {
    id: "pb-3-1",
    description: "Contabilizei maio",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-2",
    description: "Contabilizei junho",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-3",
    description: "Acordo OAB abril",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-4",
    description: "Acordo OAB maio",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-5",
    description: "Acordo OAB junho",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-6",
    description: "Plano TIM",
    amount: 130.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },
  {
    id: "pb-3-7",
    description: "Plano VIVO maio",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-8",
    description: "Plano VIVO junho",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-9",
    description: "Óculos Pai 1 de 7",
    amount: 199.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },

  // --- ESPERAR (Total: R$ 6.507,00) ---
  {
    id: "pb-w-1",
    description: "Repasse Brunner",
    amount: 1800.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Parceria divisão de processos",
  },
  {
    id: "pb-w-2",
    description: "Óculos e Lente",
    amount: 1840.00,
    scope: TransactionScope.PERSONAL,
    status: "ESPERAR",
    groupType: "WAIT",
  },
  {
    id: "pb-w-3",
    description: "Ajustes VextriaHub",
    amount: 2000.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Prestação serviços TI LegalTech",
  },
  {
    id: "pb-w-4",
    description: "Mentoria Dr Antônio",
    amount: 867.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Mentoria de gestão estratégica",
  },
];
